### PR TITLE
Clean up editor/display_folded

### PR DESCRIPTION
**Pull request by aaronfranke**
If you'd like to do this yourself, you can add this to your `~/.bash_aliases`:

    alias gdedit="find . -name '*.tscn' -exec sed -i '/^editor\//d' {} \;"

If you are on Windows, you can use WSL or Cygwin.

### CODE REVIEW

**Comment by jebedaia360** [comment]
What?
I don't understand why I should open scenes files using gedit?

**Comment by aaronfranke** [comment]
That's not gedit, that's just what I called the alias because it removes `editor/display_folded` from Godot files. You could call it "apples" instead:

    alias apples="find . -name '*.tscn' -exec sed -i '/^editor\//d' {} \;"

**Comment by jebedaia360** [comment]
Okey, but I still don't understand why I should run this command.

**Comment by aaronfranke** [comment]
Putting it in your `~/.bash_aliases` lets you go to any Godot project and run `apples` (or whatever you name the alias) to get rid of `editor/display_folded` lines if you wanted to do it yourself. I've already ran the command for you which is what this pull request is.

**Pull request merged**
